# H2 Database Configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/data/dev
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  messages:
    basename: "bundles/messages"
    useCodeAsDefaultMessage: true

management.tracing.propagation.type: b3_multi
