name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build & Test
        run: ./gradlew clean build
  static-analysis-coverage:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Identify and filter touched files
        run: |
          changed_files_main=$(git diff --name-only main github.event.pull_request.head.sha | grep '^src/main/')
          echo "::set-output name=changed_files_main::$changed_files_main"
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Run tests with JaCoCo
        run: |
          ./gradlew clean test jacocoTestReport -PfilteredFiles=$touched_files
      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: gradle-coverage-data-jacoco
          path: build/reports/jacoco/test
      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
            QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: "-i,/,--linter,jetbrains/qodana-jvm:2023.3-eap"
          pr-mode: false